# Generated by Django 3.0.5 on 2020-06-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='MEDIA_ROOT/images/%Y/%m/%d/'),
        ),
    ]
