# Generated by Django 3.0.5 on 2020-06-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_total_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='total_views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
